module.exports = {
  BAD_REQUEST_STATUS_CODE: 400,
  NOT_FOUND_STATUS_CODE: 404,
  SERVER_STATUS_CODE: 500,
  FORBIDDEN_STATUS_CODE: 403,
  CREATED_STATUS_CODE: 201,
  CONFLICT_STATUS_CODE: 409,
  DATABASE_ERROR_CODE: 11000,
  UNAUTHORIZED_STATUS_CODE: 401,
};
